// Your test code examples go here. Make sure you console.log() results.

console.log('Executing one:')
console.log(md.one('h1'))
console.log('Executing all:')
console.log(md.all('tr'))
console.log('Executing remove:')
console.log(md.remove('img'))
console.log('Executing addClass:')
console.log(md.addClass('td','active'))
console.log('Executing removeClass:')
console.log(md.removeClass('nav','navbar'))
console.log('Executing hasClass:')
console.log(md.hasClass('div','col-sm-3'))
console.log('Executing getAttr:')
console.log(md.getAttr('table'))
console.log('Executing setAttr:')
console.log(md.setAttr('table', 'active'))
console.log('Executing setHTML:')
console.log(md.setHTML('td', 'HELPHELPHELP'))
console.log('Executing getHTML:')
console.log(md.getHTML('td'))
